### ISSUE TITLE
ссылка на requirements.txt который отсутствует в ветке

### ISSUE THREAD

**Issue by Evgene-Kopylov** [j0schihatake/NN_llama_cpp_docker#1]
https://github.com/j0schihatake/NN_llama_cpp_docker/blob/375883ac068f9257d38980d44e46edfca84ff539/Dockerfile#L57C18-L57C75

**Comment by j0schihatake** [comment]
Дружище, этот файл в самом github llama.cpp. Юзай ветку py_server.
